// --- Retro Obby Monster-Killer ---
// All graphics auto-generated by script (no images needed!)

const canvas = document.getElementById('game-canvas');
const ctx = canvas.getContext('2d');
const gui = {
  health: document.getElementById('gui-health'),
  lives: document.getElementById('gui-lives'),
  level: document.getElementById('gui-level'),
  score: document.getElementById('gui-score'),
};
const menu = document.getElementById('main-menu');
const startBtn = document.getElementById('start-btn');
const characterDivs = document.querySelectorAll('.character');

let currentCharacter = "melkin";
let gameState = "menu"; // menu, playing, gameover
let player, monsters, level, score, health, lives, currentLevel;

// --- GAME OBJECTS ---
function resetPlayer() {
  player = {
    x: 32, y: 208, vx: 0, vy: 0,
    w: 16, h: 24,
    dir: 1,
    onGround: false,
    attackFrame: 0,
    character: currentCharacter,
  };
  health = 3;
}

function resetMonsters(monsterDefs) {
  monsters = monsterDefs.map(def => ({
    x: def.x,
    y: def.y,
    w: 16,
    h: 16,
    type: def.type,
    hp: 1,
    dir: Math.random() < 0.5 ? -1 : 1,
    alive: true,
  }));
}

function loadLevel(n) {
  currentLevel = n;
  const levels = [
    {
      tiles: [
        "........................",
        "........................",
        "...................M....",
        "........................",
        ".............####.......",
        "........................",
        "......###...............",
        "........................",
        "########################"
      ],
      monsters: [{x: 320, y: 176, type: 'monster1'}]
    },
    {
      tiles: [
        "........................",
        "........................",
        "....................M...",
        "....................#...",
        "............#####.......",
        "........................",
        ".....###.........###....",
        "........................",
        "########################"
      ],
      monsters: [{x: 380, y: 128, type: 'monster1'}]
    }
  ];
  let lvl = levels[n % levels.length];
  level = lvl;
  resetPlayer();
  resetMonsters(lvl.monsters);
}

// --- INPUT HANDLING ---
const keys = {};
window.addEventListener('keydown', e => {
  keys[e.code] = true;
});
window.addEventListener('keyup', e => {
  keys[e.code] = false;
});

// --- GAME LOOP ---
function update() {
  if (gameState !== "playing") return;

  // Movement
  let speed = 2;
  if (keys['ArrowLeft']) { player.vx = -speed; player.dir = -1; }
  else if (keys['ArrowRight']) { player.vx = speed; player.dir = 1; }
  else player.vx = 0;

  // Jump
  if (keys['Space'] && player.onGround) {
    player.vy = -6;
    player.onGround = false;
  }

  // Gravity
  player.vy += 0.35;
  player.y += player.vy;
  player.x += player.vx;

  // Collision (simplified)
  let ground = 232;
  if (player.y + player.h > ground) {
    player.y = ground - player.h;
    player.vy = 0;
    player.onGround = true;
  }

  // Obby tiles
  for (let y = 0; y < level.tiles.length; ++y) {
    for (let x = 0; x < level.tiles[0].length; ++x) {
      if (level.tiles[y][x] === "#") {
        let tx = x * 16, ty = y * 16;
        if (rectsCollide(player, {x: tx, y: ty, w: 16, h: 16})) {
          // Push player up
          if (player.vy > 0) {
            player.y = ty - player.h;
            player.vy = 0;
            player.onGround = true;
          } else if (player.vy < 0) {
            player.y = ty + 16;
            player.vy = 0;
          }
        }
      }
    }
  }

  // Attack
  if (keys['KeyZ'] && player.attackFrame === 0) {
    player.attackFrame = 10;
  }
  if (player.attackFrame > 0) player.attackFrame--;

  // Monster logic
  for (const m of monsters) {
    if (!m.alive) continue;
    m.x += m.dir * 1;
    if (Math.random() < 0.01) m.dir *= -1;

    // Collide with player
    if (rectsCollide(player, m)) {
      if (player.attackFrame > 0 && Math.abs(player.x - m.x) < 20) {
        m.hp -= 1;
        if (m.hp <= 0) {
          m.alive = false;
          score += 100;
        }
      } else {
        health -= 1;
        if (health <= 0) {
          lives -= 1;
          if (lives > 0) {
            resetPlayer();
          } else {
            gameState = "gameover";
          }
        }
      }
    }
  }

  // Level end: reach far right
  if (player.x > 480) {
    loadLevel(currentLevel + 1);
    score += 500;
  }
}

function draw() {
  ctx.fillStyle = "#222";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // Background
  ctx.fillStyle = "#384c6d";
  ctx.fillRect(0, 0, canvas.width, canvas.height / 2);

  // Tiles
  for (let y = 0; y < level.tiles.length; ++y) {
    for (let x = 0; x < level.tiles[0].length; ++x) {
      let t = level.tiles[y][x];
      if (t === "#") {
        ctx.fillStyle = "#666";
        ctx.fillRect(x*16, y*16, 16, 16);
        ctx.strokeStyle = "#888";
        ctx.strokeRect(x*16, y*16, 16, 16);
      }
    }
  }

  // Monsters
  for (const m of monsters) {
    if (!m.alive) continue;
    drawMonster(m.x, m.y, m.w, m.h);
  }

  // Player
  drawPlayer();

  // GUI
  gui.health.textContent = "♥ ".repeat(health);
  gui.lives.textContent = `Lives: ${lives}`;
  gui.level.textContent = `Level ${currentLevel+1}/50`;
  gui.score.textContent = `Score: ${score}`;
}

// --- Sprites drawn by script ---
function drawPlayer() {
  // MElkin: skinny, big forehead, weird hair
  let { x, y, w, h, dir } = player;
  ctx.save();
  ctx.translate(x + w/2, y + h/2);
  ctx.scale(dir, 1);
  ctx.translate(-w/2, -h/2);

  // legs
  ctx.fillStyle = "#e0d1b7";
  ctx.fillRect(6, 16, 4, 8);

  // body
  ctx.fillStyle = "#2b4291";
  ctx.fillRect(5, 8, 6, 10);

  // arms
  ctx.fillStyle = "#e0d1b7";
  ctx.fillRect(2, 10, 3, 5);
  ctx.fillRect(11, 10, 3, 5);

  // head (big forehead)
  ctx.fillStyle = "#f2e7cf";
  ctx.fillRect(3, 0, 10, 11);

  // wild hair (black squiggle)
  ctx.fillStyle = "#222";
  ctx.fillRect(5, 0, 2, 2);
  ctx.fillRect(10, -2, 2, 4);
  ctx.fillRect(7, -3, 2, 4);

  // face
  ctx.fillStyle = "#222";
  ctx.fillRect(8, 6, 2, 2);

  // attack
  if (player.attackFrame > 0) {
    ctx.fillStyle = "#fff";
    ctx.fillRect(15, 10, 7, 7);
  }
  ctx.restore();
}

function drawMonster(x, y, w, h) {
  ctx.save();
  ctx.translate(x, y);
  // body
  ctx.fillStyle = "#7d2e2e";
  ctx.fillRect(0, 4, w, h-4);
  // head
  ctx.fillStyle = "#b13b3b";
  ctx.fillRect(2, 0, w-4, 8);
  // eyes
  ctx.fillStyle = "#fff";
  ctx.fillRect(4, 3, 2, 2);
  ctx.fillRect(10, 3, 2, 2);
  ctx.fillStyle = "#000";
  ctx.fillRect(5, 4, 1, 1);
  ctx.fillRect(11, 4, 1, 1);
  // teeth
  ctx.fillStyle = "#fff";
  ctx.fillRect(7, 12, 2, 2);
  ctx.restore();
}

// --- UTILS ---
function rectsCollide(a, b) {
  return a.x < b.x + b.w && a.x + a.w > b.x &&
         a.y < b.y + b.h && a.y + a.h > b.y;
}

// --- MENU AND GAME START ---
let selectedChar = "melkin";
characterDivs.forEach(div => {
  div.addEventListener('click', () => {
    characterDivs.forEach(d => d.classList.remove('selected'));
    div.classList.add('selected');
    selectedChar = div.dataset.char;
  });
});
startBtn.addEventListener('click', async () => {
  menu.style.display = "none";
  canvas.style.display = "block";
  document.getElementById('gui').style.display = "flex";
  currentCharacter = selectedChar;
  score = 0; lives = 3;
  loadLevel(0);
  gameState = "playing";
  gameLoop();
});

// --- GAME LOOP ---
function gameLoop() {
  if (gameState === "playing") {
    update();
    draw();
  } else if (gameState === "gameover") {
    ctx.fillStyle = "#000a";
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.fillStyle = "#fff";
    ctx.font = "24px monospace";
    ctx.fillText("GAME OVER", 170, 160);
    ctx.font = "12px monospace";
    ctx.fillText("Refresh page to play again", 165, 195);
  }
  requestAnimationFrame(gameLoop);
}

// --- INIT ---
window.onload = () => {
  characterDivs[0].classList.add('selected');
};
